### ISSUE TITLE
[Android] Can't run example without modifying XR Plugin Management version.

### ISSUE THREAD

**Issue by timbotimbo** [jamesncl/flutter_embed_unity#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unity version

- [X] I am using Unity 2022.3 LTS

### Common issues

- [X] I have checked the common issues

### Flutter version

3.7.12

### Description

I downloaded Unity 2022.3.8, opened the example Unity project and triggered an Android export.

The export fails with the following message
![manifest_error](https://github.com/jamesncl/flutter_embed_unity/assets/11444698/9fcb0274-1502-4e38-8d3b-bc86e7a04c98)

##
This is a Unity bug that I noticed earlier in flutter_unity_widget.
The XR Plugin Management plugin deletes your androidmanifest in versions 4.3.1 - 4.3.3.
(You need 4.2.2 or 4.4+)

However most Unity 2022.3 versions will auto install a broken verison. (4.3.3 in my case).

(This was the reason why I removed AR dependencies from the default example in the other repo, because this fully blocks anyone from trying android without troubleshooting).

### What platforms are you seeing the problem on?

Android

### Devices

Unity on windows 10

**Comment by jamesncl** [comment]
Thanks for the bug report and the thorough explanation! That's incredibly helpful. 

So, this should be fixable by manually pinning the `com.unity.xr.management` dependency in the example project to v4.4.0 which [contains the fix](https://issuetracker.unity3d.com/issues/android-xr-xr-management-package-equals-4-dot-3-1-deletes-unitylibrary-androidmanifest-dot-xml-when-exporting-a-gradle-build). Will do that now. 

I figure it's good to keep the AR in the example if we can, as it seems to be a common reason people want to embed Unity in Flutter.

**Comment by timbotimbo** [comment]
You might want to document it somewhere too, as you get the same when creating a new project instead of using the example.

I assume this sorts itself out over time as future LTS versions move to 4.4 by default.

**Comment by jamesncl** [comment]
Yeah good call. I tried to catch the error in the build script, but weirdly the Unity reports as build succeeded with no error messages, so I've added this to the common issues section as you suggested

**Comment by learntoflutter** [comment]
@timbotimbo just so you know, this package is now [published on pub.dev](https://pub.dev/packages/flutter_embed_unity)
